{
 "title": "Observability Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": { "query": "label_values(up, namespace)" } },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(up{namespace=\"$namespace\"}, service)"
    }
   },
   {
    "name": "jvm_memory_pool_heap",
    "label": "JVM Memory Pools Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"heap\"}, id)"
    }
   },
   {
    "name": "jvm_memory_pool_nonheap",
    "label": "JVM Memory Pools Non-Heap",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", area=\"nonheap\"}, id)"
    }
   },
   {
    "name": "jvm_buffer_pool",
    "label": "JVM Buffer Pool",
    "query": {
     "query": "label_values(jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$service\"}, id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Request", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Http Request Rate Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (rate(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}[1m]) * 60)",
     "legendFormat": "code={{status}}, handler={{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", status=~\"2..|3..\"}[$__range]))",
     "legendFormat": "code={{status}}, handler={{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status, method, uri) (increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\"}[$__range]))",
     "legendFormat": "code={{status}}, handler={{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Error Requests/ Total Successful Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", status=~\"4..|5..\"}[$__range])) or vector(0)) / clamp_min(sum(increase(http_server_requests_seconds_count{namespace=\"$namespace\", service=\"$service\", status=~\"2..|3..\"}[$__range])), 1)",
     "legendFormat": "error/success"
    }
   ]
  },
  {
   "title": "ClassLoading",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Class Current Loading",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Class Loaded",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_count_classes_total{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Start Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{namespace=\"$namespace\", service=\"$service\"}) * 1000",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{namespace=\"$namespace\", service=\"$service\"} or process_files_open_files{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true
  },
  {
   "title": "JVM Memory Pool(Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{id}} used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{id}} committed"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_heap\"}",
     "legendFormat": "{{id}} max"
    }
   ]
  },
  {
   "title": "JVM Memory Pool(Non-Heap)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{id}} used"
    },
    {
     "expr": "jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{id}} committed"
    },
    {
     "expr": "jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_memory_pool_nonheap\"}",
     "legendFormat": "{{id}} max"
    }
   ]
  },
  {
   "title": "JVM Duration Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{namespace=\"$namespace\", service=\"$service\"}[5m])",
     "legendFormat": "{{service}} {{action}} {{cause}}"
    }
   ]
  },
  {
   "title": "Buffer Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{namespace=\"$namespace\", service=\"$service\", id=~\"$jvm_buffer_pool\"}",
     "legendFormat": "{{id}} used"
    }
   ]
  },
  {
   "title": "JVM Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total Time For Garbage Collection Per Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "jvm_gc_pause_seconds_sum{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}} {{action}} {{cause}}"
    }
   ]
  },
  { "title": "CPU Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 }, "repeat": "service" },
  {
   "title": "CPU Usage Per Service",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU Ratio Used Per Service",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"$namespace\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "JVM CPU Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Total CPU Usage Rate (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Top 5 Rate Using CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "topk(5, rate(process_cpu_seconds_total{namespace=\"$namespace\"}[5m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory Used After Last Garbage Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  { "title": "Memory Observability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "Memory Usage Per Service (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum by(service) (jvm_memory_used_bytes{namespace=\"$namespace\", service=\"$service\"}) / 1048576",
     "legendFormat": "{{service}} used"
    }
   ]
  },
  {
   "title": "Memory committed (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
   "targets": [
    {
     "expr": "sum by(service) (jvm_memory_committed_bytes{namespace=\"$namespace\", service=\"$service\"}) / 1048576",
     "legendFormat": "{{service}} committed"
    }
   ]
  },
  {
   "title": "Memory limit (Mb)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 94 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(service) (jvm_memory_max_bytes{namespace=\"$namespace\", service=\"$service\"}) / 1048576",
     "legendFormat": "{{service}} max"
    }
   ]
  },
  {
   "title": "Prometheus Memory Used (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
   "targets": [
    {
     "expr": "avg_over_time(process_resident_memory_bytes{namespace=\"$namespace\", service=\"$service\"}[5m]) / 1048576",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Database Connection Observability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true
  },
  {
   "title": "Max Connection Allowed",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "jdbc_connections_max{namespace=\"$namespace\", service=\"$service\"} or hikaricp_connections_max{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  },
  {
   "title": "Number Of Connection In Use",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "repeat": "job",
   "targets": [
    {
     "expr": "jdbc_connections_active{namespace=\"$namespace\", service=\"$service\"} or hikaricp_connections_active{namespace=\"$namespace\", service=\"$service\"}",
     "legendFormat": "{{service}} {{name}}"
    }
   ]
  }
 ]
}