hostname: identity.yas.local.com
backofficeRedirectUrl: https://backoffice.yas.local.com
storefrontRedirectUrl: https://storefront.yas.local.com
postgresql:
  username: yasadminuser
  password: admin

bootstrapAdmin:
  username: admin
  password: admin
