spring:
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - SaveSession
          routes:
            - id: nextjs
              uri: http://storefront-nextjs:3000
              predicates:
                - Path=/**
