apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  external:
    url: http://prometheus-grafana
    adminPassword:
      name: prometheus-grafana    # Đổi sang Secret thực tế của Grafana
      key: admin-password        # Đổi key sang admin-password
    adminUser:
      name: prometheus-grafana    # Đổi sang Secret thực tế của Grafana
      key: admin-user            # Đổi key sang admin-user