apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway
        access: proxy
        jsonData:
          httpMethod: GET
          maxLines: 1000
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: '(?:traceId=|trace_id=|"trace_id":"|"traceId":")([A-Fa-f0-9]{16,32})'
              name: traceId
              url: '$${__value.raw}'
