config:
  clients:
    - url: http://loki-gateway/loki/api/v1/push
  snippets:
    pipelineStages:
      - docker: {}
    extraRelabelConfigs:
      - source_labels:
          - app
        target_label: service_name
