pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Checkout customer-service branch'
            }
        }

        stage('Test Customer') {
            steps {
                sh '''
                cd customer
                mvn test
                '''
            }
        }

        stage('Build Customer') {
            steps {
                sh '''
                cd customer
                mvn clean package -DskipTests
                '''
            }
        }
    }

    post {
        always {
            junit 'customer/target/surefire-reports/*.xml'
        }
    }
}

