pipeline {
    agent any

    tools {
        maven 'Maven'
        jdk 'JDK21'
    }

    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'java -version'
                sh 'mvn -version'
            }
        }

        stage('Test & Coverage') {
            steps {
                sh """
                    mvn -pl location -am test jacoco:report \
                      -Djava.version=21 \
                      -Dmaven.compiler.source=21 \
                      -Dmaven.compiler.target=21 \
                      -Dsurefire.excludes='**/*IT.java,**/*IT\$*.java,**/ProductCdcConsumerTest.java,**/ProductVectorRepositoryTest.java,**/VectorQueryTest.java'
                """
            }
            post {
                always {
                    junit allowEmptyResults: true, testResults: 'location/target/surefire-reports/*.xml'
                    jacoco(
                        execPattern: 'location/target/jacoco.exec',
                        classPattern: 'location/target/classes',
                        sourcePattern: 'location/src/main/java',
                        minimumLineCoverage: '80',
                        minimumBranchCoverage: '80',
                        changeBuildStatus: true
                    )
                }
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -pl location -am package -DskipTests'
            }
        }
    }
}
